Repository realBULK/Server, pull requests merged in 2025-01, with the labels that each got.

#2 [CHORE] 초기 CI/CD 파이프라인 설정
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: :construction_worker: CI

#10 [CHORE] Spring security 설정
  build.gradle
  src/main/java/umc7th/bulk/global/config/SecurityConfig.java
Labels: :sparkles: feature

#15 [CHORE] UserService 코드 수정
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: 🛠 fix

#16 [FEAT] : 캐릭터, 일주일 식단, 하루 식단, 하루 식단-음식, 음식 엔티티 설정
  src/main/java/umc7th/bulk/character/entity/BulkCharacter.java
  src/main/java/umc7th/bulk/dayplan/entity/DayOfWeek.java
  src/main/java/umc7th/bulk/dayplan/entity/DayPlan.java
  src/main/java/umc7th/bulk/food/entity/Food.java
  src/main/java/umc7th/bulk/meal/entity/Meal.java
  src/main/java/umc7th/bulk/meal/entity/MealType.java
  src/main/java/umc7th/bulk/mealFood/entity/mealFood.java
Labels: :sparkles: feature

#18 [Feat] BaseTimeEntity 설정 및 닉네임 중복 확인 API 구현
  .gitignore
  src/main/java/umc7th/bulk/BulkApplication.java
  src/main/java/umc7th/bulk/global/BaseTimeEntity.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/UserController.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserRequestDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
  src/main/java/umc7th/bulk/user/exception/UserErrorCode.java
  src/main/java/umc7th/bulk/user/exception/UserException.java
  src/main/java/umc7th/bulk/user/repository/UserRepository.java
  src/main/java/umc7th/bulk/user/service/UserQuestionService.java
  src/main/java/umc7th/bulk/user/service/UserQuestionServiceImpl.java
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: :sparkles: feature

#20 [Feat] api 구현
  src/main/java/umc7th/bulk/user/controller/UserController.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserRequestDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
  src/main/java/umc7th/bulk/user/repository/UserRepository.java
  src/main/java/umc7th/bulk/user/service/UserQuestionService.java
  src/main/java/umc7th/bulk/user/service/UserQuestionServiceImpl.java
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: :sparkles: feature

#24 [Feat] 홈 관련 API 구현
  src/main/java/umc7th/bulk/character/repository/BulkCharacterRepository.java
  src/main/java/umc7th/bulk/dayplan/entity/DayPlan.java
  src/main/java/umc7th/bulk/food/entity/Food.java
  src/main/java/umc7th/bulk/meal/entity/Meal.java
  src/main/java/umc7th/bulk/user/controller/HomeController.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: :sparkles: feature

#26 [Feat] 전체 식단 조회 API 구현
  src/main/java/umc7th/bulk/dailyMeal/dto/DailyMealDTO.java
  src/main/java/umc7th/bulk/dailyMeal/entity/DailyMeal.java
  src/main/java/umc7th/bulk/food/entity/Food.java
  src/main/java/umc7th/bulk/meal/dto/MealDTO.java
  src/main/java/umc7th/bulk/meal/entity/Meal.java
  src/main/java/umc7th/bulk/meal/entity/MealType.java
  src/main/java/umc7th/bulk/meal/exception/MealErrorCode.java
  src/main/java/umc7th/bulk/meal/exception/MealErrorException.java
  src/main/java/umc7th/bulk/mealFood/entity/mealFood.java
  src/main/java/umc7th/bulk/mealItem/dto/MealItemDTO.java
  src/main/java/umc7th/bulk/mealItem/entity/MealItem.java
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
  src/main/java/umc7th/bulk/mealPlan/dto/MealPlanResponseDTO.java
  src/main/java/umc7th/bulk/mealPlan/entity/DayOfWeek.java
  src/main/java/umc7th/bulk/mealPlan/entity/MealPlan.java
  src/main/java/umc7th/bulk/mealPlan/exception/MealPlanErrorCode.java
  src/main/java/umc7th/bulk/mealPlan/exception/MealPlanException.java
  src/main/java/umc7th/bulk/mealPlan/repository/MealPlanRepository.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryService.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryServiceImpl.java
Labels: :sparkles: feature

#27 [FEAT] : 그룹 관련 Api 개발
  build.gradle
  docker-compose.yml
  src/main/java/umc7th/bulk/emojiRecord/entity/EmojiRecord.java
  src/main/java/umc7th/bulk/emojiRecord/repository/EmojiRecordRepository.java
  src/main/java/umc7th/bulk/global/apiPayload/CustomResponse.java
  src/main/java/umc7th/bulk/global/error/GeneralErrorCode.java
  src/main/java/umc7th/bulk/global/error/exception/CustomException.java
  src/main/java/umc7th/bulk/group/controller/GroupController.java
  src/main/java/umc7th/bulk/group/dto/EmojiDto.java
  src/main/java/umc7th/bulk/group/dto/GroupMapResponseDto.java
  src/main/java/umc7th/bulk/group/dto/TodayMemberDto.java
  src/main/java/umc7th/bulk/group/entity/Group.java
  src/main/java/umc7th/bulk/group/repository/GroupRepository.java
  src/main/java/umc7th/bulk/group/service/GroupService.java
  src/main/java/umc7th/bulk/stageRecord/dto/StageInfoDto.java
  src/main/java/umc7th/bulk/stageRecord/entity/StageRecord.java
  src/main/java/umc7th/bulk/stageRecord/repository/StageRecordRepository.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/repository/UserRepository.java
  src/main/java/umc7th/bulk/userEmoji/entity/UserEmoji.java
  src/main/java/umc7th/bulk/userEmoji/repository/UserEmojiRepository.java
Labels: :sparkles: feature

#29 [FEAT] : 특정 식단 상세 조회 API 구현
  src/main/java/umc7th/bulk/dailyMeal/exception/DailyMealErrorCode.java
  src/main/java/umc7th/bulk/dailyMeal/exception/DailyMealException.java
  src/main/java/umc7th/bulk/dailyMeal/repository/DailyMealRepository.java
  src/main/java/umc7th/bulk/meal/controller/MealController.java
  src/main/java/umc7th/bulk/meal/dto/MealDTO.java
  src/main/java/umc7th/bulk/meal/dto/MealResponseDTO.java
  src/main/java/umc7th/bulk/meal/entity/Meal.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryService.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryServiceImpl.java
  src/main/java/umc7th/bulk/mealItem/dto/MealItemDTO.java
  src/main/java/umc7th/bulk/mealItem/entity/MealItem.java
  src/main/java/umc7th/bulk/mealItem/repository/MealItemRepository.java
  src/main/java/umc7th/bulk/mealMealItemMapping/entity/MealMealItemMapping.java
  src/main/java/umc7th/bulk/mealMealItemMapping/repository/MealMealItemMappingRepository.java
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
Labels: :recycle: refactor, :sparkles: feature

#30 [FEAT] 이모지 CRUD API 구현
  .run/BulkApplication.run.xml
  src/main/java/umc7th/bulk/emojiRecord/controller/EmojiRecordController.java
  src/main/java/umc7th/bulk/emojiRecord/dto/EmojiRecordRequestDto.java
  src/main/java/umc7th/bulk/emojiRecord/dto/EmojiRecordResponseDto.java
  src/main/java/umc7th/bulk/emojiRecord/entity/EmojiRecord.java
  src/main/java/umc7th/bulk/emojiRecord/repository/EmojiRecordRepository.java
  src/main/java/umc7th/bulk/emojiRecord/service/EmojiRecordService.java
  src/main/java/umc7th/bulk/emojiRecord/service/EmojiRecordServiceImpl.java
  src/main/java/umc7th/bulk/userEmoji/controller/UserEmojiController.java
  src/main/java/umc7th/bulk/userEmoji/repository/UserEmojiRepository.java
  src/main/java/umc7th/bulk/userEmoji/service/UserEmojiService.java
  src/main/java/umc7th/bulk/userEmoji/service/UserEmojiServiceImpl.java
Labels: :sparkles: feature
