Repository realBULK/Server, pull requests merged in 2025-02, with the labels that each got.

#34 [ERROR] emoji 삭제 에러 해결
  src/main/java/umc7th/bulk/emojiRecord/service/EmojiRecordServiceImpl.java
  src/main/java/umc7th/bulk/userEmoji/repository/UserEmojiRepository.java
Labels: :bug: bug

#37 [ERROR] 기록 등록 API 에러 해결
  src/main/java/umc7th/bulk/mealMealItemMapping/repository/MealMealItemMappingRepository.java
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
  src/main/java/umc7th/bulk/userEmoji/repository/UserEmojiRepository.java
Labels: :bug: bug

#39 [FEAT] 끼니의 특정 음식 삭제 api
  src/main/java/umc7th/bulk/global/error/handler/ExceptionAdvice.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryServiceImpl.java
  src/main/java/umc7th/bulk/mealMealItemMapping/controller/MealMealItemMappingController.java
  src/main/java/umc7th/bulk/mealMealItemMapping/exception/MealMealItemMappingErrorCode.java
  src/main/java/umc7th/bulk/mealMealItemMapping/exception/MealMealItemMappingErrorException.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandService.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandServiceImpl.java
Labels: :sparkles: feature

#41 [REFACTOR] 유저 관련 필드 이름 변경 및 추가
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
Labels: :recycle: refactor, :sparkles: feature

#44 [FIX] Builder.Default 어노테이션 사용
  src/main/java/umc7th/bulk/group/entity/Group.java
  src/main/java/umc7th/bulk/record/entity/Record.java
Labels: 🛠 fix

#46 [BUG] 스프링 프레임워크 버전 다운그레이드
  build.gradle
Labels: :bug: bug

#48 [REFACTOR] 기록 등록 request body로 통일
  src/main/java/umc7th/bulk/record/controller/RecordController.java
  src/main/java/umc7th/bulk/record/dto/RecordRequestDto.java
  src/main/java/umc7th/bulk/record/service/RecordService.java
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
Labels: :recycle: refactor

#54 [FIX] CI/CD 에러 수정
  gradle/wrapper/gradle-wrapper.properties
Labels: 🛠 fix

#57 [FIX] Build 에러 수정
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: 🛠 fix

#59 [Feat] 식단 등록 API
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealCommandService.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealCommandServiceImpl.java
  src/main/java/umc7th/bulk/emojiRecord/controller/EmojiRecordController.java
  src/main/java/umc7th/bulk/emojiRecord/dto/EmojiRecordRequestDto.java
  src/main/java/umc7th/bulk/meal/entity/Meal.java
  src/main/java/umc7th/bulk/meal/repository/MealRepository.java
  src/main/java/umc7th/bulk/meal/service/command/MealCommandService.java
  src/main/java/umc7th/bulk/meal/service/command/MealCommandServiceImpl.java
  src/main/java/umc7th/bulk/mealItem/exception/MealItemErrorCode.java
  src/main/java/umc7th/bulk/mealItem/exception/MealItemErrorException.java
  src/main/java/umc7th/bulk/mealItem/service/command/MealItemCommandService.java
  src/main/java/umc7th/bulk/mealItem/service/command/MealItemCommandServiceImpl.java
  src/main/java/umc7th/bulk/mealMealItemMapping/dto/MealMealItemMappingRequestDTO.java
  src/main/java/umc7th/bulk/mealMealItemMapping/entity/MealMealItemMapping.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandService.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandServiceImpl.java
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
  src/main/java/umc7th/bulk/mealPlan/dto/MealPlanRequestDTO.java
  src/main/java/umc7th/bulk/mealPlan/dto/MealPlanResponseDTO.java
  src/main/java/umc7th/bulk/mealPlan/entity/MealPlan.java
  src/main/java/umc7th/bulk/mealPlan/service/command/MealPlanCommandService.java
  src/main/java/umc7th/bulk/mealPlan/service/command/MealPlanCommandServiceImpl.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
  src/main/java/umc7th/bulk/user/repository/UserRepository.java
Labels: :sparkles: feature, 🛠 fix

#62 [FEAT] 후기 관련 API 구현
  src/main/java/umc7th/bulk/global/error/BaseErrorCode.java
  src/main/java/umc7th/bulk/mealItem/entity/MealItem.java
  src/main/java/umc7th/bulk/review/controller/ReviewController.java
  src/main/java/umc7th/bulk/review/dto/MealItemReviewResponseDto.java
  src/main/java/umc7th/bulk/review/dto/ReviewRequestDto.java
  src/main/java/umc7th/bulk/review/dto/ReviewResponseDto.java
  src/main/java/umc7th/bulk/review/entity/Review.java
  src/main/java/umc7th/bulk/review/exception/ReviewErrorCode.java
  src/main/java/umc7th/bulk/review/exception/ReviewErrorException.java
  src/main/java/umc7th/bulk/review/repository/ReviewRepository.java
  src/main/java/umc7th/bulk/review/service/ReviewService.java
Labels: :sparkles: feature

#64 [REFACTOR] api path 통일
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/UserController.java
Labels: :recycle: refactor

#66 [Refactor] 리다이렉트 경로 변경
  src/main/java/umc7th/bulk/character/repository/BulkCharacterRepository.java
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
  src/main/java/umc7th/bulk/user/controller/HomeController.java
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: :recycle: refactor

#67 [Fix] : 식단 생성 API 관련 오류 수정
  src/main/java/umc7th/bulk/dailyMeal/dto/DailyMealDTO.java
  src/main/java/umc7th/bulk/mealPlan/dto/MealPlanRequestDTO.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryServiceImpl.java
  src/main/java/umc7th/bulk/review/entity/Review.java
Labels: :bug: bug, :recycle: refactor, 🛠 fix

#69 [FEAT] 인기 식품 조회 API
  src/main/java/umc7th/bulk/mealItem/controller/MealItemController.java
  src/main/java/umc7th/bulk/mealItem/dto/MealItemDTO.java
  src/main/java/umc7th/bulk/mealItem/entity/MealItem.java
  src/main/java/umc7th/bulk/mealItem/repository/MealItemRepository.java
  src/main/java/umc7th/bulk/mealItem/service/MealItemService.java
  src/main/java/umc7th/bulk/mealItem/service/MealItemServiceImpl.java
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
  src/main/java/umc7th/bulk/user/service/UserService.java
Labels: :sparkles: feature

#76 [FIX] 새로운 사용자 로그인 URL 수정
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
Labels: 🛠 fix

#74 [FIX] cascade 참조 수정
  src/main/java/umc7th/bulk/mealItem/entity/MealItem.java
  src/main/java/umc7th/bulk/mealMealItemMapping/entity/MealMealItemMapping.java
Labels: :bug: bug, 🛠 fix

#79 [FIX] 식단 상세 조회 page 오류 수정
  src/main/java/umc7th/bulk/meal/controller/MealController.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryServiceImpl.java
  src/main/java/umc7th/bulk/mealMealItemMapping/repository/MealMealItemMappingRepository.java
Labels: :recycle: refactor, 🛠 fix

#83 [FIX] emoji url 수정
  src/main/java/umc7th/bulk/emojiRecord/controller/EmojiRecordController.java
Labels: 🛠 fix

#86 [FIX] CORS 설정 추가
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: 🛠 fix

#88 [FIX] Group 관련 API 수정
  src/main/java/umc7th/bulk/group/controller/GroupController.java
  src/main/java/umc7th/bulk/group/service/GroupService.java
Labels: 🛠 fix

#89 [FEAT] 오늘 식단 조회 API
  src/main/java/umc7th/bulk/dailyMeal/controller/DailyMealController.java
  src/main/java/umc7th/bulk/dailyMeal/dto/DailyMealResponseDTO.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealService.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealServiceImpl.java
  src/main/java/umc7th/bulk/meal/dto/MealDTO.java
  src/main/java/umc7th/bulk/mealItem/dto/MealItemDTO.java
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
  src/main/java/umc7th/bulk/mealPlan/service/command/MealPlanCommandServiceImpl.java
Labels: :sparkles: feature

#91 [FIX] 백엔드 도메인 CORS 추가
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: 🛠 fix

#98 [FEAT] 검색 음식 상세 조회 API 구현
  src/main/java/umc7th/bulk/mealItem/controller/MealItemController.java
  src/main/java/umc7th/bulk/mealItem/dto/MealItemDTO.java
  src/main/java/umc7th/bulk/mealItem/repository/MealItemRepository.java
  src/main/java/umc7th/bulk/mealItem/service/MealItemService.java
  src/main/java/umc7th/bulk/mealItem/service/MealItemServiceImpl.java
Labels: :sparkles: feature

#93 [FIX] CORS 필터 수정
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/WelcomeController.java
Labels: 🛠 fix

#95 [FEAT] token 받는 api 추가
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/UserController.java
Labels: :sparkles: feature

#100 [FEAT] 인가코드 받아서 token 발급 API 구현
  src/main/java/umc7th/bulk/dailyMeal/dto/DailyMealDTO.java
  src/main/java/umc7th/bulk/dailyMeal/dto/DailyMealResponseDTO.java
  src/main/java/umc7th/bulk/user/config/KakaoOAuth2Config.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/AuthController.java
  src/main/java/umc7th/bulk/user/controller/UserController.java
  src/main/java/umc7th/bulk/user/dto/KakaoTokenResponse.java
  src/main/java/umc7th/bulk/user/service/KakaoAuthService.java
Labels: :bug: bug, :sparkles: feature

#108 [FIX] 리다이렉트 경로 배포 서버로 수정
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
Labels: :bug: bug

#110 [FIX] 무한 리다이렉트 수정
  src/main/java/umc7th/bulk/user/config/OAuth2LoginSuccessHandler.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: :bug: bug

#112 [FEAT] 이메일 로그인 기능 추가
  build.gradle
  src/main/java/umc7th/bulk/global/config/WebConfig.java
  src/main/java/umc7th/bulk/global/jwt/exception/AuthException.java
  src/main/java/umc7th/bulk/global/jwt/exception/JwtErrorCode.java
  src/main/java/umc7th/bulk/global/jwt/filter/JwtFilter.java
  src/main/java/umc7th/bulk/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/umc7th/bulk/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/umc7th/bulk/global/jwt/util/JwtProvider.java
  src/main/java/umc7th/bulk/user/annotation/CurrentUser.java
  src/main/java/umc7th/bulk/user/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
  src/main/java/umc7th/bulk/user/controller/HomeController.java
  src/main/java/umc7th/bulk/user/controller/UserController.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/dto/UserRequestDTO.java
  src/main/java/umc7th/bulk/user/dto/UserResponseDTO.java
  src/main/java/umc7th/bulk/user/enums/UserStatus.java
  src/main/java/umc7th/bulk/user/exception/UserErrorCode.java
  src/main/java/umc7th/bulk/user/principal/PrincipalDetails.java
  src/main/java/umc7th/bulk/user/principal/PrincipalDetailsService.java
  src/main/java/umc7th/bulk/user/repository/UserRepository.java
  src/main/java/umc7th/bulk/user/service/command/UserCommandService.java
  src/main/java/umc7th/bulk/user/service/command/UserCommandServiceImpl.java
  src/main/java/umc7th/bulk/user/service/query/UserQueryService.java
  src/main/java/umc7th/bulk/user/service/query/UserQueryServiceImpl.java
Labels: :sparkles: feature

#117 [FEAT] 홈 영양정보 조회 기능 구현
  src/main/java/umc7th/bulk/record/controller/RecordController.java
  src/main/java/umc7th/bulk/record/dto/RecordResponseDto.java
  src/main/java/umc7th/bulk/record/repository/RecordRepository.java
  src/main/java/umc7th/bulk/record/service/RecordService.java
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
Labels: :sparkles: feature

#118 [FIX] 식단 관련 사용자 접근 제한
  src/main/java/umc7th/bulk/dailyMeal/controller/DailyMealController.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealService.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealServiceImpl.java
  src/main/java/umc7th/bulk/meal/controller/MealController.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryService.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryServiceImpl.java
  src/main/java/umc7th/bulk/mealMealItemMapping/controller/MealMealItemMappingController.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandService.java
  src/main/java/umc7th/bulk/mealMealItemMapping/service/command/MealMealItemMappingCommandServiceImpl.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryServiceImpl.java
Labels: 🛠 fix

#122 [FIX]cors 문제
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: 🛠 fix

#124 [FIX] 그룹 자동 생성 구현
  src/main/java/umc7th/bulk/group/entity/Group.java
  src/main/java/umc7th/bulk/group/repository/GroupRepository.java
  src/main/java/umc7th/bulk/user/config/KakaoOAuth2Config.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/service/UserService.java
  src/main/java/umc7th/bulk/user/service/command/UserCommandServiceImpl.java
Labels: 🛠 fix

#127 [FIX] 식단 기록 시 유저 엔티티에 영양정보 저장하도록 수정
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
  src/main/java/umc7th/bulk/user/domain/User.java
  src/main/java/umc7th/bulk/user/service/command/UserCommandServiceImpl.java
Labels: 🛠 fix

#129 Fix: Config 파일에 PATCH 추가
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: 🛠 fix

#132 [FEAT] 사용자 MealPlanId 확인 API
  src/main/java/umc7th/bulk/mealPlan/controller/MealPlanController.java
  src/main/java/umc7th/bulk/mealPlan/dto/MealPlanResponseDTO.java
  src/main/java/umc7th/bulk/mealPlan/exception/MealPlanErrorCode.java
  src/main/java/umc7th/bulk/mealPlan/repository/MealPlanRepository.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryService.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryServiceImpl.java
Labels: :sparkles: feature

#134 [FIX] record 기록 시 그룹에 필요한 정보 업데이트 수정
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
  src/main/java/umc7th/bulk/stageRecord/entity/StageRecord.java
  src/main/java/umc7th/bulk/stageRecord/repository/StageRecordRepository.java
  src/main/java/umc7th/bulk/user/service/command/UserCommandServiceImpl.java
Labels: 🛠 fix

#137 [REFACTOR] sql 식단 조회 쿼리 최적화
  src/main/java/umc7th/bulk/dailyMeal/repository/DailyMealRepository.java
  src/main/java/umc7th/bulk/dailyMeal/service/command/DailyMealServiceImpl.java
  src/main/java/umc7th/bulk/meal/service/query/MealQueryServiceImpl.java
  src/main/java/umc7th/bulk/mealPlan/service/query/MealPlanQueryServiceImpl.java
Labels: :recycle: refactor

#139 [FIX] 식단대로 먹었을 시의 기록 응답 구체화
  src/main/java/umc7th/bulk/global/error/GeneralErrorCode.java
  src/main/java/umc7th/bulk/record/service/RecordServiceImpl.java
Labels: 🛠 fix

#136 [CHORE] 깃 액션 동작 수정
  .github/workflows/gradle.yml
Labels: :construction_worker: CI

#141 [FIX] 프론트 배포 서버 추가
  src/main/java/umc7th/bulk/user/config/SecurityConfig.java
Labels: 🛠 fix
